config/routes.rb
Unmute::Application.routes.draw do

  resources :users do
    resources :comments
  end
  
  resources :categories

  resources :posts do 
    member { post :vote }
    resources :comments
  end

  root :to => 'categories#show', :id => '1'
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'users/:id' => 'users#show', as: :user

end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name, :color
	has_many :categorizations
	has_many :posts, :through => :categorizations
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    # @posts = @category.posts.order("created_at DESC").paginate(:per_page => 1, :page => params[:page])
    @posts = @category.posts.reverse

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  
# disabling creation of new categories for now
#   def new
#     @category = Category.new
#     @user = current_user

#     respond_to do |format|
#       format.html # new.html.erb
#       format.json { render json: @category }
#     end
#   end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categorywell.html.erb
  <div class="row" style="margin-top:-22px">
  	<div class="span6">
  		<div class="well" style="text-align:center; border-radius: 0px; border-top:2px solid black; background-color:<%= @category.color %>; color:white">
  			<h1 style="font-family: lato; padding: 20px;">  			
  				<div class="dropdown" style="margin: 0px auto 20px auto; display:inline-block">
  					<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
  						<span style="font-size:32px;color:<%= @category.color %>">
  							<%= @category.name %>
  						</span>
  						<span class="caret" style="margin-top:-15px;margin-left:10px; color:<%= @category.color %>"></span>
  					</button>
  					<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/posts">All</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/1">Popular</a></li>
  						<li role="presentation" class="divider"></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/2">Animals</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/3">Art</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/4">Comedy</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/5">Dating</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/6">Education</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/7">Family</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/8">Food</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/9">Music & Dance</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/10">News</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/11">Politics</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/12">Science & Tech</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/13">Sex</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/14">Sports</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/15">Style</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/16">Travel</a></li>
  						<li role="presentation"><a role="menuitem" tabindex="-1" href="/categories/17">Other</a></li>
  					<!-- <li role="presentation" class="divider"></li>
  					<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Surprise Me</a></li> -->
  				</ul>
        </div> stories of <%= Date.today.to_formatted_s(:long_ordinal) %><br></h1>
  		</div>
  	</div>
  </div>

app/views/categories/_form.html.erb
<!-- <%= simple_form_for(@category) do |f| %>
<% if @category.errors.any? %>
<% @categories.errors.full_messages.each do |msg| %>
<div class="errors">
  <%= msg %>
</div>
<% end %>
<% end %>
<div class="write-post">
  <div id="header">
    <%= f.text_field :name, placeholder: "Name", class: "write-post", :autocomplete => :off %>
    <%= f.text_field :color, placeholder: "Color", class: "write-post", :autocomplete => :off %>
  </div>  
  <%= f.button :submit, 'Done', class: "post-button" %>
  
</div>

<% end %> -->

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <!--<td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

<br />

<!-- <%= link_to 'New Category', new_category_path %> -->

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= render 'categorywell' %>
<div class="row">
<div class="col-lg-12">

		<% @posts.each do |post| if post.publish == true %>
		<table id="post-table">
			<tr>
				<td rowspan="3" onclick=window.location='/posts/<%= post.id %>' style="cursor: pointer; width:160px">
					<%= image_tag post.image.url(:medium) %>

					<td id="table-title" onclick=window.location='/posts/<%= post.id %>' style="cursor: pointer;"><%= post.title %>
					</td>
					<tr>
						<td id="table-body" onclick=window.location='/posts/<%= post.id %>' style="cursor: pointer;">	
							<%= truncate(post.body, :length => 225) %>
						</td>
					</tr>
					<tr>
						<td id="table-actions">
							<strong>Anonymous author &mdash; <% if post.user.followers_twitter.between?(0,1000) %> 500ish <% else %> <%= number_with_delimiter(post.user.followers_twitter.round(-3), :delimiter => ',') %>ish<% end %> followers</strong> <% Category.find(post.category_ids).each do |c| %> 

							<button type="button" onclick=window.location='/categories/<%= c.id %>' class="header-category" style="background-color:<%= c.color %>">
								<%= c.name %>
							</button>


							<% end %> <!-- &middot; <span class="glyphicon glyphicon-heart-empty"><%= Random.new.rand(5..3000) %></span> -->
					<!-- <% if current_user == post.user %>
					<%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Delete', post, method: :delete, data: { confirm: 'You sure, bro or brodette?' } %>
					<% end %> -->
				</td>
			</tr>
		</td>
	</tr>
</table>
<% end %>
<% end %>

<% if @posts.count == 0 %>
<div class="write-post">
	<form action="/posts/new">
		<input class="new-post-button" type="submit" value="No posts in <%= @category.name %> today. Get writin'!">
	</form>
</div>
<% else %>

<div class="write-post">
	<form action="/posts/new">
		<input class="new-post-button" type="submit" value="Start writing">
	</form>
</div>
<% end %>


</div>
</div>
<!--<%= Post.find(@category.post_ids).each do |post| %>
<%= post.title %>
<% end %> -->
<!-- <%= link_to 'Edit', edit_category_path(@category) %> |
	<%= link_to 'Back', categories_path %> -->